---
# tasks file for install-avamar-linux

  - block:
    - name: Create temp directory Linux
      file:
       path: "{{ temp_directory_linux }}"
       state: directory
    when: ansible_facts['os_family'] == "RedHat"

  - block:
    - name: Copy files Linux x86
      copy:
       src: "{{ temp_directory_agents }}/{{ agent_linux_x86 }}"
       dest: "{{ temp_directory_linux }}/AvamarClient-linux-sles11-x86-19.1.100-38.rpm"

    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['userspace_bits'] == "32"


  - block:
    - name: Copy files Linux x64
      copy:
       src: "{{ temp_directory_agents }}/{{ agent_linux_x64 }}"
       dest: "{{ temp_directory_linux }}/AvamarClient-linux-sles11-x86_64-18.2.100-134.rpm"

    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['userspace_bits'] == "64"

  - block:
    - name: Installation agent on Linux x86
      yum:
       name: "{{ temp_directory_linux }}/AvamarClient-linux-sles11-x86-19.1.100-38.rpm"
       state: present
    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['userspace_bits'] == "32"


  - block:
    - name: Installation agent on Linux x64
      yum:
       name: "{{ temp_directory_linux }}/AvamarClient-linux-sles11-x86_64-18.2.100-134.rpm"
       state: present
    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['userspace_bits'] == "64"

  - block:
    - name: Registration agent Linux
      command: "{{ linux_bin_path }} {{ avamar_server }} {{ avamar_domain }}"
    when: ansible_facts['os_family'] == "RedHat"

